name    'davinci'
version '1.0.0'
source  'git://github.com/cafuego/davinci.git'
author  'cafuego'
license 'GPL License, Version 2.0'
summary 'UNKNOWN'
description 'maintain a sensible garbage file via puppet'
project_page 'https://github.com/cafuego/davinci'
